### ISSUE TITLE
Option to not use ini file?

### ISSUE THREAD

**Issue by jackttcoms** [HTMLGuyLLC/PHPReCaptcha#1]
HI is it possible to not use the ini file for the secret key? Thanks

**Comment by jackttcoms** [comment]
Thanks

**Comment by HTMLGuyLLC** [comment]
NP

**Comment by HTMLGuyLLC** [comment]
Lol there we go. I couldn't get Packagist to update. I was making a few mistakes. Whew I'm tired. Enjoy and let me know if there are any issues. I wrote the changes directly into Github, but it should be right.

**Comment by jackttcoms** [comment]
Thankyou very much! Really appreciate it and also your very quick support! Also is it ok if I include this with my framework as a come-in-box feature? Thanks

Note: I'll let you know if I find any bugs!

**Comment by HTMLGuyLLC** [comment]
Sure, it's MIT licensed so just make sure you include a reference to the source and license. Thanks! (Plus I'd appreciate a heads up on where it's used. Always neat to see)

**Comment by jackttcoms** [comment]
Of course! It's not ready yet but when it is I will link to it :)

Thanks again!
